Address deprecation warning
esensar/nvim-dev-container pull request #78
Opened 2023-05-25 12:30 UTC by MajorZiploc

To address the following warning from nvim v0.9 when parsing the jsonc devcontainer file:

```
vim.treesitter.parse_query() is deprecated, use vim.treesitter.query.parse_query() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```

2023-05-25 14:16 UTC, gyurikol approved these changes

2023-05-25 14:18 UTC, gyurikol requested changes
`parse_query()` isn't it :thinking:

2023-05-25 14:30 UTC, MajorZiploc commented
ah. actually, `parse_query()` is also deprecated
i changed it to that and then I got a deprecation warning about parse_query() and to use `.parse()`
sorry, should have mentioned that

2023-05-25 14:37 UTC, MajorZiploc commented
heres the warning message I get when using `parse_query()`
```
vim.treesitter.query.parse_query() is deprecated, use vim.treesitter.query.parse() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```

2023-05-26 11:05 UTC, esensar approved these changes
Thank you!

2023-05-26 11:06 UTC, merged